name: XcraftSocial
version: 1.0.3
author: INemesisI
description: Requires XcraftLibrary v1.6.2

main: de.xcraft.INemesisI.Social.XcraftSocial
load: POSTWORLD

depend: [XcraftLibrary]

commands:
  social:
    aliases: s
  friend:
    aliases: f
  group:
    aliases: g
  gc:
  fl:
  gl:


permissions:
    xcraftsocial.admin:
        children:
            xcraftsocial.save: true
            xcraftsocial.reload: true
            xcraftsocial.friend.add.exempt: true
        default: op
    xcraftsocial.friend:
        children:
            xcraftsocial.friend.add: true
            xcraftsocial.friend.remove: true
            xcraftsocial.friend.accept: true
            xcraftsocial.friend.decline: true
            xcraftsocial.friend.list: true
        default: true
    xcraftsocial.group:
        children:
            xcraftsocial.group.add: true
            xcraftsocial.group.chat: true
            xcraftsocial.group.create: true
            xcraftsocial.group.delete: true
            xcraftsocial.group.info: true
            xcraftsocial.group.kick: true
            xcraftsocial.group.leave: true
            xcraftsocial.group.list: true
            xcraftsocial.group.toggle: true
        default: true
            
